# 欢迎使用 Jekyll!
#
# 这个配置文件用于设置影响整个博客的设置，这些值
# 你通常只需要设置一次，很少需要再次编辑。如果你发现
# 自己经常编辑这个文件，考虑使用 Jekyll 的数据文件
# 功能来存储需要经常更新的数据。
#
# 由于技术原因，当你使用 'bundle exec jekyll serve' 时，
# 这个文件不会自动重新加载。如果你修改了这个文件，请重启服务器进程。
#
# 如果你需要 YAML 语法帮助，这里有一些快速参考：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 网站设置
# 这些用于个性化你的新网站。如果你查看HTML文件，
# 你会看到它们通过 {{ site.title }}、{{ site.email }} 等方式被访问。
# 你可以创建任何你喜欢的自定义变量，它们将可以
# 在模板中通过 {{ site.myvariable }} 访问。

title: gongxh
email: gong.xinhai@163.com
description: >- # 这意味着忽略换行符直到 "baseurl:"
  拥有10+年游戏开发经验的技术分享平台，专注于Cocos Creator游戏开发。
  深度分享开发工具使用、踩坑经验总结、技术原理解析，
  致力于帮助游戏开发者提升技能，携手共同成长。
baseurl: "" # 用户站点不需要子路径
url: "https://gongxh0901.github.io" # 网站的基础主机名和协议，例如 https://gongxh.github.io

# 联系方式
github_username: gongxh0901
gitee_username: gongxinhai  # 国内Gitee仓库
wechat_id: G0900901  # 微信号，可在关于页面显示

# 构建设置 - 使用GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Jekyll配置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# GitHub Pages设置
safe: true
source: .
destination: ./_site
keep_files: [".git", ".svn"]
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# 编码
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass配置
sass:
  style: compressed
  sass_dir: _sass
  cache: false

# 自定义设置
author:
  name: "gongxh"
  bio: "10+年游戏开发老兵，专注Cocos Creator技术分享与开发者成长"
  
# 项目展示
featured_projects:
  - name: "Cocos Creator开发框架"
    description: "高效的游戏开发工具链与框架"
    tech: "Cocos Creator, TypeScript"
    url: "https://github.com/gongxh/cocos-framework"
  - name: "H5小游戏合集" 
    description: "微信小游戏与H5游戏项目"
    tech: "Cocos Creator, 微信小程序"
    url: "https://github.com/gongxh/h5-games"
  - name: "性能优化工具集"
    description: "游戏性能分析与优化工具"
    tech: "Cocos Creator, 性能调优"
    url: "https://gitee.com/gongxh/performance-tools"

# 排除处理的文件
# 以下项目默认不会被处理。
# 在"排除："键下列出的任何项目都会自动添加到
# 内部"默认列表"中。
#
# 排除的项目可以通过在"包含："列表中明确列出目录或
# 其条目的文件路径来处理。
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .cursor-rules  # 排除 Cursor 规则文件
